version: "3"
services: 
  database: 
    image: "postgres:latest"
    volumes: 
      - ./server/database:/var/lib/postgresql/data
    networks: 
      - my_network
    container_name: database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: database
    ports: 
      - "5432:5432"

  server:
    networks: 
      - my_network
    build: ./server
    ports: 
      - "3001:3001" 
    container_name: server
    depends_on: 
      - database
    environment:
      DB_CONNECTION_STRING: postgres://postgres:docker@database:5432/database
    volumes: 
      -  ./server:/app

  frontend: 
    networks: 
      - my_network
    build: ./front-end
    ports: 
      - "3000:3000"
    container_name: frontend
    depends_on: 
      - server
    volumes: 
      -  ./front-end:/app

networks:  
  my_network: 
    driver: bridge

  

     